name: CI

on:
    push:
        branches: [main]
    pull_request: {}

jobs:
    test:
        name: Node.js v${{ matrix.nodejs }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                nodejs: [12, 14, 15, 16]
        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                  node-version: ${{ matrix.nodejs }}

            - name: (env) pnpm
              run: curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm

            - name: (env) cache
              uses: actions/cache@main
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-node${{ matrix.nodejs }}-${{
                      hashFiles('./package.json', './yarn.lock') }}
                  restore-keys: ${{ runner.os }}-node${{ matrix.nodejs }}-

            - name: Install
              run: pnpm install

            - name: Type Check
              run: pnpm run typecheck

            - name: Compile
              run: pnpm run build
